name: flutter_fortune_wheel
description: Visualize (random) selection processes with widgets like a spinning wheel of fortune or a fortune bar.
repository: https://github.com/kevlatus/flutter_fortune_wheel
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  auto_route: ^2.3.0
  flutter:
    sdk: flutter

  flutter_hooks: ^0.17.0
  quiver: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  effective_dart: ^1.3.1
